version: 2.1

# -------------------------------------------------------------------------------
# Jobs
# -------------------------------------------------------------------------------

jobs:

  build:
    parameters:
      test_google_api:
        type: boolean
        default: false
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Build and run checks
          command: ./gradlew build -x example-with-google-api:test
      - when:
          condition: << parameters.test_google_api >>
          steps:
            - run:
                name: Test Google API
                command: |
                  echo $GCLOUD_SERVICE_KEY > /tmp/_key.json
                  export GOOGLE_APPLICATION_CREDENTIALS=/tmp/_key.json
                  ./gradlew run :runExampleWithGoogle
            - run:
                command: rm /tmp/_key.json
                when: always
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
          when: always

# -------------------------------------------------------------------------------
# Workflows
# -------------------------------------------------------------------------------

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          test_google_api: true
